site_name: LeagueProject

site_url: https://renecotyfanboy.github.io/leagueProject/

nav:
  - Home: index.md
  - Dataset:
    - dataset/introduction.md
    - dataset/cookbook.md
  - Around the LoserQ:
    - loserQ/motivation.md
    - loserQ/model.md
    - loserQ/validation.md
    - loserQ/true_data.md
  - Around trueskill2:
    - trueskill2/introduction.md
  - Reference:
    - data : api/data.md
    - model : api/model.md
    - inference : api/inference.md
    - plot : api/plot.md



theme:
  name: material
  icon:
    favicon: simple/leagueoflegends
    logo: simple/leagueoflegends
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode`
  features:
    #- navigation.instant
    #- navigation.instant.progress
    #- navigation.instant.prefetch
    - navigation.tracking
    - content.footnote.tooltips
    #- toc.integrate
    - navigation.sections
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.tooltips

plugins:
  - search
  - autorefs
  - typeset
  - macros:
      include_yaml:
        - true_data : docs/loserQ/assets/true_data_result.yml
  - plotly:
      lib_path: javascripts/plotly-2.32.0.js
      template_slate: plotly_dark
  - glightbox:
      auto_caption: false
      caption_position: bottom
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            members_order: alphabetical
            docstring_section_style: spacy
            docstring_style: google
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            modernize_annotations: true

use_directory_urls: true

markdown_extensions:
  - abbr
  - attr_list
  - tables
  - md_in_html
  - meta
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - css/material.css

extra:
  generator: false

#extra_css:
#  - css/material.css
